version: '3.4'

services:
  scheduleserviceapi:
    image: scheduleserviceapi
    build:
      context: .
      dockerfile: ScheduleService.API/Dockerfile
    networks:
      - local
    environment:
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=youtube
    volumes:
      - ~/.aspnet/https:/https
    depends_on:
      - db
  db:
    image: postgres:16.2-alpine3.19
    container_name: scheduleApiDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scheduleApiDb
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d scheduleApiDb'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - local
    volumes:
      - posgres_data:/var/lib/postgresql/data
networks:
  local:
    driver: bridge
volumes:
  posgres_data:
    driver: local
