using FluentMigrator;

namespace ScheduleService.Infrastructure.Migrations;

[Migration(20241029190629)]
public class Initial_20241029190629 : Migration
{
    public override void Down()
    {
        Delete.Table(TableNames.SUBJECTS);
        Delete.Table(TableNames.SPECIAL_SUBJECTS);
        Delete.Table(TableNames.TEACHERS_SUBJECTS);
        Delete.Table(TableNames.TEACHERS_SUBJECTS_GROUPS);
        Delete.Table(TableNames.ROOMS);
        Delete.Table(TableNames.WEEKDAYS);
        Delete.Table(TableNames.SCHEDULES);
        Delete.Table(TableNames.ROOMS_SCHEDULES);
        Delete.Table(TableNames.SCHEDULES_TEACHERS_SUBJECTS);
    }

    public override void Up()
    {
        Create
            .Table(TableNames.SUBJECTS)
            .WithColumn("id")
            .AsInt32()
            .PrimaryKey()
            .Identity()
            .WithColumn("name")
            .AsString(64)
            .WithColumn("abbreviation")
            .AsString(16);
        Create
            .Table(TableNames.SPECIAL_SUBJECTS)
            .WithColumn("subject_fk")
            .AsInt32()
            .ForeignKey(
                $"fk_{TableNames.SPECIAL_SUBJECTS}_{TableNames.SUBJECTS}",
                TableNames.SUBJECTS,
                "id"
            )
            .OnDelete(System.Data.Rule.Cascade)
            .WithColumn("speciality_fk")
            .AsInt32()
            .WithColumn("course")
            .AsByte();
        Create
            .Table(TableNames.TEACHERS_SUBJECTS)
            .WithColumn("id")
            .AsInt32()
            .PrimaryKey()
            .Identity()
            .WithColumn("teacher_fk")
            .AsGuid()
            .WithColumn("subject_fk")
            .AsInt32()
            .ForeignKey(
                $"fk_{TableNames.TEACHERS_SUBJECTS}_{TableNames.SUBJECTS}",
                TableNames.SUBJECTS,
                "id"
            )
            .OnDelete(System.Data.Rule.Cascade);
        Create
            .Table(TableNames.TEACHERS_SUBJECTS_GROUPS)
            .WithColumn("teacher_subject_fk")
            .AsInt32()
            .ForeignKey(
                $"fk_{TableNames.TEACHERS_SUBJECTS_GROUPS}_{TableNames.TEACHERS_SUBJECTS}",
                TableNames.TEACHERS_SUBJECTS,
                "id"
            )
            .OnDelete(System.Data.Rule.Cascade);
        Create
            .Table(TableNames.ROOMS)
            .WithColumn("room")
            .AsString(10)
            .PrimaryKey()
            .WithColumn("full_name")
            .AsString(128)
            .Nullable();
        Create
            .Table(TableNames.WEEKDAYS)
            .WithColumn("order")
            .AsByte()
            .PrimaryKey()
            .WithColumn("name")
            .AsString(16)
            .WithColumn("abbreviation")
            .AsString(3);
        Create
            .Table(TableNames.SCHEDULES)
            .WithColumn("id")
            .AsInt32()
            .PrimaryKey()
            .Identity()
            .WithColumn("group_fk")
            .AsInt32()
            .WithColumn("weekday_fk")
            .AsByte()
            .ForeignKey(
                $"fk_{TableNames.SCHEDULES}_{TableNames.WEEKDAYS}",
                TableNames.WEEKDAYS,
                "order"
            )
            .OnDelete(System.Data.Rule.Cascade)
            .WithColumn("changed_at")
            .AsDateTime()
            .Nullable()
            .WithColumn("ends_at")
            .AsDateTime()
            .WithColumn("starts_at")
            .AsDateTime()
            .WithColumn("irrelevant_since")
            .AsDateTime()
            .Nullable();
        Create
            .Table(TableNames.ROOMS_SCHEDULES)
            .WithColumn("room_fk")
            .AsString()
            .ForeignKey(
                $"fk_{TableNames.ROOMS_SCHEDULES}_{TableNames.ROOMS}",
                TableNames.ROOMS,
                "room"
            )
            .OnDelete(System.Data.Rule.Cascade)
            .WithColumn("schedule_fk")
            .AsInt32()
            .ForeignKey(
                $"fk_{TableNames.ROOMS_SCHEDULES}_{TableNames.SCHEDULES}",
                TableNames.SCHEDULES,
                "id"
            )
            .OnDelete(System.Data.Rule.Cascade);
        Create
            .Table(TableNames.SCHEDULES_TEACHERS_SUBJECTS)
            .WithColumn("schedule_id")
            .AsInt32()
            .ForeignKey(
                $"fk_{TableNames.SCHEDULES_TEACHERS_SUBJECTS}_{TableNames.SCHEDULES}",
                TableNames.SCHEDULES,
                "id"
            )
            .OnDelete(System.Data.Rule.Cascade)
            .WithColumn("teachers_subject_id")
            .AsInt32()
            .ForeignKey(
                $"fk_{TableNames.SCHEDULES_TEACHERS_SUBJECTS}_{TableNames.TEACHERS_SUBJECTS}",
                TableNames.TEACHERS_SUBJECTS,
                "id"
            )
            .OnDelete(System.Data.Rule.Cascade);
    }
}
